"""The supplement knowledge base: evidence-graded, research-backed, honest.

Every entry was distilled from current evidence summaries (examine.com, ISSN
position stands, NIH ODS fact sheets, meta-analyses) by research agents.
The verdict tiers are deliberately blunt — the product's job is telling users
what is a true supplement and what is garbage:

    proven      — the real ones: strong evidence, clear effect
    solid       — moderate evidence; worth it for the right training
    situational — real, but only if YOU specifically need it (test/context first)
    weak        — evidence too thin to justify the money
    garbage     — marketing in a tub

This KB grounds the AI advisor's prompt AND renders as the in-app Supplement
Library. It is reference information, not medical advice.
"""

VERDICTS = ("proven", "solid", "situational", "weak", "garbage")

KB = [
    # ── health & micronutrients ─────────────────────────────────────────
    {
        "id": "vitamin-d3",
        "name": "Vitamin D3",
        "category": "health",
        "verdict": "situational",
        "evidence_for": "Corrects deficiency; supports bone, immune and muscle function. Performance gains only in deficient people.",
        "dose": "1000–2000 IU/day maintenance; 4000–5000 IU/day for 8–12 weeks to correct a tested deficiency. UL 4000 IU/day.",
        "timing": "Daily with a meal containing fat; time of day irrelevant.",
        "pros": ["Deficiency is very common (winter, indoor training, dark skin)",
                 "Pennies per day, well tolerated",
                 "Strength/sprint gains reported in deficient athletes",
                 "Supports calcium absorption and bone density"],
        "cons": ["No benefit if already sufficient",
                 "Hypercalcemia risk with years of high dosing",
                 "Ideally test 25(OH)D first"],
        "best_for": "Low sun exposure, northern winters, indoor lifters, dark skin, 50+.",
        "skip_if": "Already replete; sarcoidosis, hyperparathyroidism, kidney-stone history, thiazide diuretics.",
    },
    {
        "id": "omega-3",
        "name": "Omega-3 Fish Oil (EPA/DHA)",
        "category": "health",
        "verdict": "solid",
        "evidence_for": "Reduces post-exercise soreness and inflammatory markers; strong triglyceride lowering. Performance effects inconsistent.",
        "dose": "2–3 g/day combined EPA+DHA, EPA-dominant; needs 6+ weeks of consistent use.",
        "timing": "Daily with a fatty meal; split doses to dodge reflux.",
        "pros": ["Meaningful soreness and inflammation reduction",
                 "Cardiometabolic support; covers low fish intake",
                 "May aid muscle protein synthesis in older adults"],
        "cons": ["Slow loading — no acute effect",
                 "Rancid products are common; buy third-party tested",
                 "High doses debated for atrial-fibrillation risk"],
        "best_for": "Athletes eating fish <2×/week, high training volume, eccentric-heavy sports, 50+.",
        "skip_if": "On blood thinners without clinician approval; pre-surgery; AFib history; fish allergy.",
    },
    {
        "id": "magnesium",
        "name": "Magnesium (glycinate/citrate)",
        "category": "health",
        "verdict": "situational",
        "evidence_for": "Corrects the common intake shortfall; modest sleep signal in people with low status. Little effect when replete.",
        "dose": "200–400 mg elemental/day (glycinate or citrate — skip oxide).",
        "timing": "Evening, 30–60 min before bed for the sleep angle.",
        "pros": ["~Half of adults under-consume it; sweat raises needs",
                 "Glycinate is well absorbed and gentle on the gut",
                 "Citrate doubles as constipation relief"],
        "cons": ["Cramp evidence is mixed", "Diarrhea above ~400 mg",
                 "Oxide form is mostly a laxative", "Status is hard to test reliably"],
        "best_for": "Heavy sweaters, poor sleepers, low-vegetable diets, high training stress.",
        "skip_if": "Chronic kidney disease; space 2+ hours from certain antibiotics and levothyroxine.",
    },
    {
        "id": "zinc",
        "name": "Zinc",
        "category": "health",
        "verdict": "situational",
        "evidence_for": "Corrects a common shortfall in athletes/vegetarians; lozenges shorten colds. No benefit above normal status.",
        "dose": "15–30 mg/day elemental with food. UL 40 mg/day.",
        "timing": "With food (empty-stomach zinc means nausea).",
        "pros": ["Cheap correction of a real athlete shortfall",
                 "Supports immunity, wound healing, hormone synthesis"],
        "cons": ["Chronic >40 mg/day causes copper deficiency and lowers HDL",
                 "Zero benefit if already replete"],
        "best_for": "Vegetarians/vegans, heavy sweaters, restrictive dieters, frequent colds.",
        "skip_if": "Already stacked to 40 mg across products; on tetracyclines/quinolones (space 2+ hours).",
    },
    {
        "id": "zma",
        "name": "ZMA (zinc-magnesium 'testosterone' blend)",
        "category": "health",
        "verdict": "garbage",
        "evidence_for": "The testosterone claim traces to one industry-funded study; independent replication found nothing in zinc-replete men.",
        "dose": "N/A as a branded blend — plain zinc and magnesium cover any real shortfall for less.",
        "timing": "Marketed pre-bed; the timing story is not evidence-based.",
        "pros": ["Contains zinc and magnesium, which can matter individually if deficient"],
        "cons": ["Testosterone marketing unsupported by independent research",
                 "Branded markup over the identical plain minerals",
                 "Encourages stacking past the zinc UL"],
        "best_for": "Nobody as a blend — buy the minerals separately if tested/needed.",
        "skip_if": "You expect hormonal effects — that's the marketing, not the data.",
    },
    {
        "id": "iron",
        "name": "Iron",
        "category": "health",
        "verdict": "situational",
        "evidence_for": "Strong endurance improvement in deficient people (test first — non-negotiable). Harmful when replete.",
        "dose": "Only after a ferritin blood test. 40–100 mg elemental/day or alternate-day dosing; retest at 6–8 weeks.",
        "timing": "Morning, empty stomach, with vitamin C; alternate days absorbs better. Not within 1 hour post-exercise.",
        "pros": ["Restores endurance, VO2 and fatigue resistance when depleted",
                 "Alternate-day dosing improves absorption ~30%", "Inexpensive"],
        "cons": ["Toxic when not needed — iron overload is real",
                 "Constipation and nausea are common",
                 "Requires blood work and follow-up"],
        "best_for": "Menstruating women (after testing), endurance athletes, vegetarians, blood donors.",
        "skip_if": "Male or postmenopausal without documented deficiency; hemochromatosis; space widely from levothyroxine, calcium, antacids.",
    },
    {
        "id": "calcium",
        "name": "Calcium",
        "category": "health",
        "verdict": "situational",
        "evidence_for": "Food calcium is the better vehicle; supplements give small bone gains with cardiovascular-risk signals in meta-analyses.",
        "dose": "Aim 1000–1200 mg/day TOTAL from diet first; supplement only the gap, ≤500 mg at a time.",
        "timing": "Split doses ≤500 mg; carbonate with food, citrate anytime.",
        "pros": ["Genuinely protective in dairy-free diets and low-energy-availability female athletes",
                 "Cheap; pairs with vitamin D and lifting for bone"],
        "cons": ["Supplement (not food) calcium linked to higher MI/stroke risk in meta-analyses",
                 "Kidney-stone risk; blocks iron and zinc absorption"],
        "best_for": "Dairy-free/vegan diets, amenorrheic athletes, postmenopausal women, stress-fracture history.",
        "skip_if": "Diet already covers 1000+ mg; kidney-stone history; on thiazides or digoxin.",
    },
    {
        "id": "multivitamin",
        "name": "Daily Multivitamin",
        "category": "health",
        "verdict": "weak",
        "evidence_for": "No mortality benefit across ~400k adults over 20 years. Cheap gap insurance for restrictive diets, nothing more.",
        "dose": "One serving of a boring ~100% DV formula. Skip mega-dose 'sport' versions.",
        "timing": "With a meal.",
        "pros": ["Very cheap insurance during aggressive cuts or restrictive diets",
                 "Modest cognitive-aging signal in 60+"],
        "cons": ["Cannot fix a poor diet and may create false reassurance",
                 "Many contain iron — wrong for most men and postmenopausal women",
                 "Overlaps with other supplements toward cumulative overdose"],
        "best_for": "Hard cuts, elimination diets, vegans, older adults, poor produce access.",
        "skip_if": "You already eat varied whole foods; choose iron-free unless tested deficient.",
    },
    {
        "id": "electrolytes",
        "name": "Electrolytes / Hydration Salts",
        "category": "health",
        "verdict": "situational",
        "evidence_for": "Real for sessions >60–90 min, heat, or heavy sweating. For a normal gym hour, food covers it.",
        "dose": "300–1000 mg sodium per liter of fluid during prolonged work; salty sweaters up to 1500 mg/L.",
        "timing": "During and after long/hot sessions; pre-load in extreme heat.",
        "pros": ["Prevents hyponatremia in long events", "Improves voluntary rehydration",
                 "Sodium is the only electrolyte with solid evidence"],
        "cons": ["Unnecessary for <60 min training", "Expensive vs water + salted food",
                 "Sodium load matters in hypertension"],
        "best_for": "Endurance work, hot climates, visibly salty sweaters, two-a-days, low-carb dieters.",
        "skip_if": "Hypertension/heart/kidney conditions without guidance; short-session gym-goers.",
    },
    {
        "id": "psyllium",
        "name": "Fiber (Psyllium Husk)",
        "category": "health",
        "verdict": "proven",
        "evidence_for": "Dose-dependent LDL/apoB reduction (~7% at 10 g/day), post-meal glucose blunting, bowel regulation both directions.",
        "dose": "5–10 g/day, started at 3–5 g and titrated over 1–2 weeks, always with 250+ mL water.",
        "timing": "30 min before meals for satiety/glycemic effect.",
        "pros": ["One of the best-evidenced non-drug LDL reducers",
                 "Satiety help on a cut", "Very cheap",
                 "Fixes the constipation high-protein diets cause"],
        "cons": ["Gas the first two weeks", "Needs real water every dose",
                 "Space 2+ hours from medications"],
        "best_for": "Anyone under 25–38 g/day of food fiber (most lifters), elevated LDL, hungry cutters.",
        "skip_if": "Bowel strictures/obstruction history, dysphagia, active IBD flare.",
    },
    {
        "id": "greens-powder",
        "name": "Greens Powders",
        "category": "health",
        "verdict": "garbage",
        "evidence_for": "Essentially no clinical trials on finished products; proprietary blends hide doses; any benefit comes from the added synthetic vitamins.",
        "dose": "No evidence-based dose exists.",
        "timing": "The 'morning ritual' framing is marketing.",
        "pros": ["Can raise micronutrient intake in people who truly eat zero vegetables"],
        "cons": ["$2.50–3.50/serving vs a $0.10 multivitamin plus real vegetables",
                 "'Proprietary blend' labels hide fairy-dust amounts",
                 "Zero meaningful fiber vs actual vegetables",
                 "Heavy-metal contamination reported in unverified brands"],
        "best_for": "Almost nobody — eat vegetables; travel convenience at best.",
        "skip_if": "You have a budget, a multivitamin, or access to a grocery store; warfarin users (variable vitamin K).",
    },
    {
        "id": "b12",
        "name": "Vitamin B12",
        "category": "health",
        "verdict": "situational",
        "evidence_for": "Essentially mandatory for vegans and valuable for 60+/metformin/PPI users; zero energy boost if you're replete.",
        "dose": "250–500 mcg/day or 1000–2000 mcg 1–2×/week.",
        "timing": "Anytime; frequency matters more than clock time.",
        "pros": ["Extremely cheap, effectively non-toxic",
                 "Prevents irreversible nerve damage from silent deficiency"],
        "cons": ["Useless as an 'energy' supplement when replete",
                 "Deficiency builds silently over years — the fix is boring consistency"],
        "best_for": "Vegans (non-negotiable), 60+, metformin and acid-blocker users.",
        "skip_if": "Normal-status omnivores expecting an energy kick — it isn't one.",
    },
    # ── performance ─────────────────────────────────────────────────────
    {
        "id": "creatine",
        "name": "Creatine Monohydrate",
        "category": "performance",
        "verdict": "proven",
        "evidence_for": "The most replicated ergogenic aid in existence: strength, high-intensity output, lean mass with training; cognitive signal in older/sleep-deprived adults.",
        "dose": "3–5 g/day, every day. Monohydrate only — fancier forms cost more and work no better.",
        "timing": "Any time; daily consistency is everything. Rest days included.",
        "pros": ["Best evidence-to-cost ratio of any legal supplement",
                 "Extra lean mass and strength on top of training",
                 "Safe long-term in healthy people (studied to 5 years)",
                 "Vegetarians/vegans respond most"],
        "cons": ["1–2 kg water weight early (matters for weight classes)",
                 "~20–30% barely respond (already-saturated stores)",
                 "Raises creatinine on lab work — an artifact, but tell your doctor"],
        "best_for": "Everyone who lifts or sprints; adults 50+ for muscle retention; women benefit equally.",
        "skip_if": "Kidney disease without physician clearance; acute weight-making athletes.",
    },
    {
        "id": "caffeine",
        "name": "Caffeine",
        "category": "performance",
        "verdict": "proven",
        "evidence_for": "Improves endurance, power, sprint work and lowers perceived effort — acutely, from the first dose.",
        "dose": "3–6 mg/kg (200–400 mg for most). More adds side effects, not performance.",
        "timing": "30–60 min pre-training. Coffee works nearly as well as pills.",
        "pros": ["Works day one, no loading", "Makes hard sessions feel easier", "Nearly free"],
        "cons": ["Sleep disruption is the real price — keep it 6–8 h from bed",
                 "Tolerance blunts the edge", "Jitters/anxiety at higher doses; response is genetic"],
        "best_for": "Endurance and team-sport athletes, morning/fasted trainers, low-motivation days.",
        "skip_if": "Evening trainers, pregnancy (limit ~200 mg/day), arrhythmia, anxiety disorders, stimulant medication.",
    },
    {
        "id": "whey",
        "name": "Whey Protein",
        "category": "performance",
        "verdict": "proven",
        "evidence_for": "The cheapest, most convenient way to hit your daily protein target — which is what actually drives muscle, not the powder itself.",
        "dose": "20–40 g per serving; the number that matters is 1.4–2.0 g/kg protein per day.",
        "timing": "Whenever it helps you hit the target. The 'anabolic window' is hours wide, not minutes.",
        "pros": ["Cheapest quality protein per gram", "Highest leucine content",
                 "Easy to drink when appetite is low", "Isolate is nearly lactose-free"],
        "cons": ["Zero advantage over food if the daily target is already met",
                 "Concentrate bloats the lactose-intolerant",
                 "Buy third-party tested brands"],
        "best_for": "Lifters, cutters, older adults (aim 35–40 g/serving), chronic protein under-eaters.",
        "skip_if": "Milk allergy (isolate or plant blends instead); protein target already covered by food.",
    },
    {
        "id": "casein",
        "name": "Casein Protein",
        "category": "performance",
        "verdict": "solid",
        "evidence_for": "Slow-digesting; pre-sleep dosing raises overnight muscle protein synthesis. Long-term difference vs whey is small.",
        "dose": "30–40 g; 40 g is the studied pre-sleep dose.",
        "timing": "Before bed, or bridging long meal gaps.",
        "pros": ["Best-evidenced use: overnight amino delivery", "Very filling — handy on a cut"],
        "cons": ["Pricier than whey for the same job", "Thick and gritty",
                 "Overnight-synthesis edge doesn't clearly become extra muscle vs equal daily protein"],
        "best_for": "Low evening protein intake, hungry-at-night cutters, older adults.",
        "skip_if": "Milk allergy; budget-limited — whey does 95% of the job.",
    },
    {
        "id": "plant-protein",
        "name": "Plant Protein Blends",
        "category": "performance",
        "verdict": "solid",
        "evidence_for": "Blends (pea+rice, soy) match whey for muscle when dose and leucine are matched. Single-source plant isolates underperform.",
        "dose": "30–40 g per serving (~1.25× a whey dose) delivering 2.5–3 g leucine.",
        "timing": "Same as whey — daily total is what counts.",
        "pros": ["Equivalent gains in recent trials when dosed right", "Dairy-free, more fiber"],
        "cons": ["Bigger servings needed — real cost per effective dose rises",
                 "Heavy-metal contamination reports are more common — buy tested brands",
                 "Standalone rice/hemp/collagen are poor choices"],
        "best_for": "Vegans, vegetarians, the dairy-intolerant.",
        "skip_if": "Buying single-source non-blended isolates or untested brands.",
    },
    {
        "id": "beta-alanine",
        "name": "Beta-Alanine",
        "category": "performance",
        "verdict": "solid",
        "evidence_for": "Buffers acidosis; real but small benefit specifically for 1–10 min max efforts. Useless for single lifts and long steady work.",
        "dose": "4–6.4 g/day split into small doses, for 4+ weeks — it loads like creatine, not like caffeine.",
        "timing": "Daily with meals; clock time irrelevant.",
        "pros": ["Genuinely helps middle-distance, rowing, CrossFit, combat sports",
                 "Cheap; stacks with creatine"],
        "cons": ["The famous tingles (harmless but annoying)", "Weeks of compliance before any effect",
                 "Small enough that many never notice it"],
        "best_for": "1–4 minute max-effort athletes and high-rep training blocks.",
        "skip_if": "Pure strength or long slow endurance goals — wrong energy system.",
    },
    {
        "id": "citrulline",
        "name": "Citrulline Malate",
        "category": "performance",
        "verdict": "weak",
        "evidence_for": "Meta-analyses show ~3 extra reps to failure — a small, inconsistent effect. The pump is real; the performance translation is modest.",
        "dose": "8 g citrulline malate or 3–6 g L-citrulline.",
        "timing": "60 min pre-training.",
        "pros": ["Modest replicated volume boost for high-volume lifters", "Well tolerated"],
        "cons": ["Small and inconsistent — untrained users often get nothing",
                 "Expensive relative to the effect", "GI upset at higher doses"],
        "best_for": "High-volume hypertrophy specialists with budget left after the proven tier.",
        "skip_if": "On nitrates, PDE5 inhibitors or blood-pressure meds (additive hypotension); tight budget.",
    },
    {
        "id": "pre-workout",
        "name": "Pre-Workout Blends",
        "category": "performance",
        "verdict": "weak",
        "evidence_for": "The measurable effect is almost entirely the caffeine. Most products under-dose everything else and hide it in proprietary blends.",
        "dose": "Judge by ingredients: caffeine 3–6 mg/kg, citrulline 6–8 g, beta-alanine 3.2 g+. Most labels don't clear the bar.",
        "timing": "20–45 min pre-training.",
        "pros": ["Convenient ritual; the caffeine genuinely works"],
        "cons": ["Proprietary blends hide sub-clinical doses",
                 "~1 in 10 supplements carries banned-substance contamination",
                 "Stimulant stacking drives heart/anxiety risk",
                 "Far pricier than buying caffeine + creatine separately"],
        "best_for": "Convenience seekers who read fully-disclosed labels and buy certified brands.",
        "skip_if": "Drug-tested without NSF/Informed Sport certification; evening training; heart conditions, anxiety; any 'proprietary blend' label.",
    },
    {
        "id": "bcaa",
        "name": "BCAAs",
        "category": "performance",
        "verdict": "garbage",
        "evidence_for": "The most oversold product in sports nutrition. Three of twenty amino acids can't build muscle, and whey already contains more BCAAs per scoop.",
        "dose": "No dose fixes the premise.",
        "timing": "Irrelevant.",
        "pros": ["May slightly reduce soreness in some trials", "At least they're safe"],
        "cons": ["Cannot maximize muscle protein synthesis — the other aminos are missing",
                 "Completely redundant with adequate protein intake",
                 "Often costs more than the whey that outperforms it"],
        "best_for": "Almost nobody — a flavored drink for fasted training at best.",
        "skip_if": "You eat protein. That's the whole story — buy whey or EAAs instead.",
    },
    {
        "id": "eaa",
        "name": "EAAs",
        "category": "performance",
        "verdict": "situational",
        "evidence_for": "Actually works (all nine essentials present) — but redundant when whole protein is adequate. Real value in older adults and appetite-limited people.",
        "dose": "10–15 g per serving with 2.5 g+ leucine.",
        "timing": "Around training or bridging long gaps; useful for fasted sessions.",
        "pros": ["Genuinely stimulates muscle protein synthesis, unlike BCAAs",
                 "Lean-mass gains shown in older adults", "Easy when food is unappealing"],
        "cons": ["Much pricier per gram than whey for the same outcome",
                 "Marketed with BCAA-style overclaims"],
        "best_for": "Older adults with poor appetite, dairy-intolerant athletes, pre-training on an empty stomach.",
        "skip_if": "Healthy adult hitting 1.4–2.0 g/kg protein — use whey or food; phenylketonuria.",
    },
    {
        "id": "glutamine",
        "name": "Glutamine",
        "category": "performance",
        "verdict": "garbage",
        "evidence_for": "Meta-analysis of 25 trials: no effect on body composition, performance, or immunity in athletes. Your body makes it; whey already contains it.",
        "dose": "No evidence-based performance dose exists.",
        "timing": "N/A.",
        "pros": ["Narrow legitimate niche: gut distress in ultra-endurance and supervised clinical illness"],
        "cons": ["Zero effect on muscle, strength, or recovery in healthy trainees",
                 "Sold on 'anti-catabolic' claims with no athlete RCT support",
                 "Money that should have bought creatine or protein"],
        "best_for": "Essentially no healthy lifter.",
        "skip_if": "Your goal is muscle or performance — that's the marketing, not the data.",
    },
    # ── recovery & specialty ────────────────────────────────────────────
    {
        "id": "ashwagandha",
        "name": "Ashwagandha",
        "category": "recovery",
        "verdict": "solid",
        "evidence_for": "Reliable cortisol/anxiety reduction and modest sleep improvement in stressed adults; strength/testosterone claims are much weaker.",
        "dose": "300–600 mg/day standardized extract (KSM-66/Sensoril); more adds nothing.",
        "timing": "With food; evening if sleep is the goal. Needs 4–8 weeks.",
        "pros": ["Consistent stress and sleep-quality signal", "Cheap; 12-month safety data at 600 mg"],
        "cons": ["Rare idiosyncratic liver-injury reports", "Can nudge thyroid hormones",
                 "Brand standardization varies wildly"],
        "best_for": "High-stress lifters, poor sleepers, hard training blocks or deficits.",
        "skip_if": "Pregnancy, thyroid conditions or levothyroxine, autoimmune disease, sedatives, liver disease.",
    },
    {
        "id": "melatonin",
        "name": "Melatonin",
        "category": "recovery",
        "verdict": "situational",
        "evidence_for": "Excellent for jet lag and shifted schedules; only a small effect on ordinary insomnia (~10 min faster sleep onset). Not a sedative.",
        "dose": "0.3–1 mg for circadian shifting; 1–3 mg for sleep onset. Higher is worse, not better.",
        "timing": "30–60 min pre-bed; for time zones, dose at destination bedtime.",
        "pros": ["Non-habit-forming, very low toxicity, dirt cheap",
                 "The best tool available for jet lag and shift work"],
        "cons": ["Small effect on regular insomnia — CBT-I beats it",
                 "US label accuracy is notoriously bad (80–470% of stated dose)",
                 "Morning grogginess and vivid dreams at higher doses"],
        "best_for": "Travelers, shift workers, evening-training athletes with delayed sleep, older adults.",
        "skip_if": "Pregnancy, anticoagulants, immunosuppressants, diabetes meds; kids without a clinician.",
    },
    {
        "id": "collagen",
        "name": "Collagen Peptides (+ Vitamin C)",
        "category": "recovery",
        "verdict": "solid",
        "evidence_for": "Reduces joint/tendon pain and improves function when paired with loading exercise. It is NOT a muscle protein — don't count it toward your target.",
        "dose": "10–15 g hydrolyzed peptides + ~50 mg vitamin C.",
        "timing": "30–60 min BEFORE tendon-loading work; give it 3–6 months.",
        "pros": ["Multiple RCTs for tendinopathy and joint pain", "Very safe", "Great rehab adjunct"],
        "cons": ["Inferior to whey for muscle — low tryptophan, incomplete",
                 "Months of consistency plus actual loading required", "Ongoing ~$1/day"],
        "best_for": "Masters athletes 35+, runners, climbers, anyone nursing tendons and joints.",
        "skip_if": "Asymptomatic joints and adequate protein — spend on the proven tier first.",
    },
    {
        "id": "glucosamine",
        "name": "Glucosamine / Chondroitin",
        "category": "recovery",
        "verdict": "weak",
        "evidence_for": "Chondroitin has a small pain signal in existing knee arthritis; the famous combo repeatedly failed to beat placebo. No preventive value for healthy joints.",
        "dose": "If trialed at all: glucosamine sulfate 1500 mg + chondroitin 800–1200 mg/day; judge at 8–12 weeks and stop if nothing.",
        "timing": "Daily with food.",
        "pros": ["Long safety record", "Small real analgesic signal in symptomatic knee OA"],
        "cons": ["Large independent trials came back negative",
                 "The commonly sold HCl form is the less-supported one",
                 "Collagen or curcumin are better bets for the same money"],
        "best_for": "Older adults with existing knee arthritis who've exhausted better options.",
        "skip_if": "Healthy young joints — zero prophylactic value; shellfish allergy; warfarin.",
    },
    {
        "id": "curcumin",
        "name": "Curcumin (bioavailable forms)",
        "category": "recovery",
        "verdict": "solid",
        "evidence_for": "Meaningful joint-pain improvement and reduced post-exercise soreness — but only in bioavailability-enhanced forms. Plain turmeric powder is functionally useless.",
        "dose": "500–2000 mg curcuminoids with piperine, or 250–1000 mg phytosome/micellar forms.",
        "timing": "Daily with a fatty meal; load around brutal eccentric sessions.",
        "pros": ["NSAID-comparable OA pain relief in some trials with better GI tolerance",
                 "Real DOMS reduction"],
        "cons": ["Piperine interacts with many medications", "Rare liver reports with enhanced forms",
                 "Chronic high-dose anti-inflammatories may blunt adaptation"],
        "best_for": "Masters athletes, joint-pain sufferers, high-volume eccentric blocks.",
        "skip_if": "Pregnancy, gallbladder disease, anticoagulants, iron-deficiency anemia, narrow-window medications.",
    },
    {
        "id": "tart-cherry",
        "name": "Tart Cherry",
        "category": "recovery",
        "verdict": "situational",
        "evidence_for": "Restores functional strength between closely-spaced hard sessions; soreness effect inconsistent. An event-week tool, not a daily habit.",
        "dose": "30 mL concentrate twice daily for 4–7 days into an event, through 48 h after.",
        "timing": "Race/tournament weeks; one serving pre-bed for the mild sleep angle.",
        "pros": ["Best evidence for short-turnaround recovery", "No doping risk"],
        "cons": ["100–250 kcal of sugar per serving", "Pricey",
                 "Chronic antioxidant loading may blunt training adaptation — don't live on it"],
        "best_for": "Tournament athletes, congested schedules, race week.",
        "skip_if": "Cutting (calorie cost), off-season base building (blunting risk), glucose management.",
    },
    {
        "id": "hmb",
        "name": "HMB",
        "category": "recovery",
        "verdict": "situational",
        "evidence_for": "Real anti-catabolic value for 50+, injury layoffs, and severe deficits. In trained young lifters eating protein: trivial. Early miracle results never replicated independently.",
        "dose": "3 g/day split into 3 doses, loaded 2+ weeks.",
        "timing": "One dose pre-training, rest with meals.",
        "pros": ["Genuinely useful for older adults and immobilization periods", "Very safe"],
        "cons": ["Redundant with adequate protein in the young and trained",
                 "The glowing literature is heavily industry-funded", "$30–50/month"],
        "best_for": "50+, aggressive cuts, injury recovery, detrained returners.",
        "skip_if": "Healthy trained lifter with protein and creatine handled — buy those instead.",
    },
    {
        "id": "fat-burners",
        "name": "Fat Burners / Thermogenics",
        "category": "recovery",
        "verdict": "garbage",
        "evidence_for": "No blend has clinically meaningful weight-loss evidence. The only working ingredient is caffeine — sold at a 50x markup.",
        "dose": "Not recommended. Plain caffeine 100–300 mg gives the same effect for pennies.",
        "timing": "N/A.",
        "pros": ["The caffeine inside genuinely suppresses appetite short-term — that's the entire honest list"],
        "cons": ["Highest-risk category for adulteration (banned stimulants, unlabeled drugs)",
                 "Drives ~20–25% of US supplement-linked liver injury",
                 "Cardiovascular events, insomnia, anxiety",
                 "The calorie deficit was always the mechanism"],
        "best_for": "Nobody. A deficit and protein do the work.",
        "skip_if": "Everyone — especially heart conditions, anxiety, liver disease, drug-tested athletes.",
    },
    {
        "id": "test-boosters",
        "name": "'Testosterone Boosters'",
        "category": "recovery",
        "verdict": "garbage",
        "evidence_for": "Systematic reviews: the large majority have zero human evidence of raising testosterone. Tribulus doesn't. D-aspartic acid failed and may lower it.",
        "dose": "Not recommended. Only correcting a tested vitamin D or zinc deficiency raises T — from deficiency only.",
        "timing": "N/A.",
        "pros": ["Ashwagandha and D/zinc repletion carry the only legitimate faint signals"],
        "cons": ["Frequent adulteration with SARMs and prohormones",
                 "Documented liver injury from spiked products",
                 "Sub-clinical doses hidden in proprietary blends",
                 "Real symptoms need a morning blood test and a physician"],
        "best_for": "Nobody. Low-T symptoms deserve a doctor, not a tub.",
        "skip_if": "Everyone — especially under-25s, drug-tested athletes, fertility-seekers, and women.",
    },
    {
        "id": "theanine",
        "name": "L-Theanine",
        "category": "recovery",
        "verdict": "situational",
        "evidence_for": "Takes the jittery edge off caffeine without dulling the alertness; standalone calming effects are subtle.",
        "dose": "100–200 mg paired 1:1 with caffeine; 200–400 mg alone for winding down.",
        "timing": "With your pre-training caffeine, or 30–60 min before bed solo.",
        "pros": ["Reliably smooths caffeine", "Excellent safety, no dependence", "Cheap"],
        "cons": ["Standalone effects are small", "No direct performance benefit"],
        "best_for": "Caffeine-sensitive trainees, anxious athletes, heavy pre-workout users.",
        "skip_if": "You tolerate caffeine fine — then it's a luxury, not a need; blood-pressure medication.",
    },
    {
        "id": "taurine",
        "name": "Taurine",
        "category": "recovery",
        "verdict": "weak",
        "evidence_for": "Small acute performance signal with low certainty of evidence — far smaller than creatine, caffeine, or beta-alanine.",
        "dose": "1–3 g about an hour pre-training (no dose-response above that).",
        "timing": "~60 min pre-exercise.",
        "pros": ["Very cheap and extremely safe", "Slight edge in heat/endurance contexts"],
        "cons": ["Low-certainty evidence, likely inflated by small studies",
                 "Redundant if you drink energy drinks or pre-workout already"],
        "best_for": "Endurance athletes in heat, budget add-on after the proven tier is covered.",
        "skip_if": "Priorities not yet covered — creatine, caffeine, protein, and sleep come first.",
    },
]


def kb_for_prompt():
    """Compact grounding block injected into the AI advisor prompt."""
    lines = []
    for s in KB:
        lines.append(
            f"- {s['name']} [{s['verdict'].upper()}]: {s['evidence_for']} "
            f"Dose: {s['dose']} Best for: {s['best_for']} Caution: {s['skip_if']}"
        )
    return "\n".join(lines)
