#!/usr/bin/env python3
"""Generate the Sunday coaching review and push it to the phone — for cron/systemd.

Run from the repo root (nutrition_data.json lives in the cwd):
    ./venv/bin/python scripts/weekly_review.py

Install as a Sunday 18:00 systemd user timer with scripts/install_review_timer.sh;
on Windows, scripts/install_windows_tasks.ps1 registers the WeeklyReview task.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app import create_app  # noqa: E402
from app import data as store, notify  # noqa: E402


def main():
    app = create_app()
    with app.test_client() as client:
        # Unattended: run the AI subprocess with a minimal environment.
        res = client.post('/api/coach', headers={'X-GNA-Unattended': '1'})
        body = res.get_json() or {}
    if res.status_code != 200:
        err = str(body.get('error', res.status))
        print(f"Weekly review failed: {err}", file=sys.stderr)
        # an empty week is a clean no-op, not a failure
        return 0 if 'nothing from the last 7 days' in err else 1
    try:
        notify.push(store.load()['settings'], 'Sunday coaching review',
                    str(body.get('summary', ''))[:400])
    except Exception:
        pass  # the review still lands in the app if the push fails
    print(f"Weekly review generated by {body.get('coach')}")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
